brasileiro = ('Botafogo', 'Palmeiras', 'Flamengo', 'Fortaleza', 'Internacional', 'São Paulo', 'Corinthians', 'Bahia', 'Cruzeiro', 'Vasco da Gama', 'Vitória', 'Atlético-MG', 'Fluminense', 'Grêmio', 'Juventude', 'Bragantino', 'Atletico-PR', 'Criciúma', 'Atletico-GO', 'Cuiabá')
print('Colocação do brasileirão 2024')
print(f'Campeão: {brasileiro[0]}')
print(f'Clasificados para libertadores: {brasileiro[0:6]}')
print(f'Pré-libertadores: {brasileiro[6:8]}')
print(f'Sul-Americana: {brasileiro[8:14]}')
print(f'Rebaixados: {brasileiro[16:20]}')
print(f'{brasileiro[14:16]} ficaram nas posições {brasileiro.index('Juventude') + 1} e {brasileiro.index('Bragantino') + 1}')
print('Os times em ordem alfabética:')
print(sorted(brasileiro))